version: "3.9"

services:
  car_service:
    build:
      context: .
      dockerfile: docker-build/car_service/Dockerfile
    environment:
      CONFIG: ProductionConfig

    ports:
      - "8000:80"

    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 7s
      timeout: 5s
      retries: 5

volumes:
  pg-data: